export const Roles = {
  GOALKEEPER: "goalkeeper",
  DEFENDER: "defender",
  MIDFIELDER: "midfielder",
  FORWARD: "forward",
};

export type RoleType = (typeof Roles)[keyof typeof Roles];

export const RolesRu = {
  [Roles.GOALKEEPER]: "ГП",
  [Roles.DEFENDER]: "З",
  [Roles.MIDFIELDER]: "ПЗ",
  [Roles.FORWARD]: "НП",
};

export const initialPlayers = [
  {
    id: 10,
    name: "Иван Андреев",
    avatar: "https://i.pravatar.cc/150?img=3",
    position: { x: null, y: null },
    role: Roles.GOALKEEPER,
  },
  {
    id: 22,
    name: "Петр Петров",
    avatar: "https://i.pravatar.cc/150?img=4",
    position: { x: null, y: null },
    role: Roles.GOALKEEPER,
  },
  {
    id: 33,
    name: "Сидор Сидоров",
    avatar: "https://i.pravatar.cc/150?img=5",
    position: { x: null, y: null },
    role: Roles.DEFENDER,
  },
  {
    id: 87,
    name: "Алексей Смирнов",
    avatar: "https://i.pravatar.cc/150?img=11",
    position: { x: null, y: null },
    role: Roles.DEFENDER,
  },
  {
    id: 42,
    name: "Михаил Козлов",
    avatar: "https://i.pravatar.cc/150?img=12",
    position: { x: null, y: null },
    role: Roles.DEFENDER,
  },
  {
    id: 16,
    name: "Дмитрий Новиков",
    avatar: "https://i.pravatar.cc/150?img=13",
    position: { x: null, y: null },
    role: Roles.DEFENDER,
  },
  {
    id: 23,
    name: "Артём Морозов",
    avatar: "https://i.pravatar.cc/150?img=14",
    position: { x: null, y: null },
    role: Roles.DEFENDER,
  },
  {
    id: 95,
    name: "Максим Волков",
    avatar: "https://i.pravatar.cc/150?img=15",
    position: { x: null, y: null },
    role: Roles.MIDFIELDER,
  },
  {
    id: 14,
    name: "Андрей Соколов",
    avatar: "https://i.pravatar.cc/150?img=16",
    position: { x: null, y: null },
    role: Roles.MIDFIELDER,
  },
  {
    id: 67,
    name: "Николай Попов",
    avatar: "https://i.pravatar.cc/150?img=17",
    position: { x: null, y: null },
    role: Roles.MIDFIELDER,
  },
  {
    id: 69,
    name: "Владимир Лебедев",
    avatar: "https://i.pravatar.cc/150?img=18",
    position: { x: null, y: null },
    role: Roles.MIDFIELDER,
  },
  {
    id: 45,
    name: "Георгий Кузнецов",
    avatar: "https://i.pravatar.cc/150?img=19",
    position: { x: null, y: null },
    role: Roles.MIDFIELDER,
  },
  {
    id: 29,
    name: "Борис Васильев",
    avatar: "https://i.pravatar.cc/150?img=20",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
  {
    id: 73,
    name: "Степан Михайлов",
    avatar: "https://i.pravatar.cc/150?img=21",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
  {
    id: 74,
    name: "Константин Павлов",
    avatar: "https://i.pravatar.cc/150?img=22",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
  {
    id: 31,
    name: "Виктор Семёнов",
    avatar: "https://i.pravatar.cc/150?img=23",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
  {
    id: 44,
    name: "Григорий Федоров",
    avatar: "https://i.pravatar.cc/150?img=24",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
  {
    id: 91,
    name: "Роман Орлов",
    avatar: "https://i.pravatar.cc/150?img=25",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
  {
    id: 68,
    name: "Денис Киселев",
    avatar: "https://i.pravatar.cc/150?img=26",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
  {
    id: 53,
    name: "Евгений Макаров",
    avatar: "https://i.pravatar.cc/150?img=27",
    position: { x: null, y: null },
    role: Roles.FORWARD,
  },
];
